# Generated by Django 3.1.1 on 2020-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(blank=True, max_length=200)),
                ('accepted', models.BooleanField(blank=True)),
                ('answers', models.IntegerField(blank=True)),
                ('body', models.CharField(blank=True, max_length=200)),
                ('closed', models.BooleanField(blank=True)),
                ('migrated', models.BooleanField(blank=True)),
                ('notice', models.BooleanField(blank=True)),
                ('tagged', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('user', models.IntegerField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('views', models.IntegerField(blank=True)),
                ('wiki', models.BooleanField(blank=True)),
                ('nottagged', models.CharField(blank=True, max_length=200)),
                ('order', models.CharField(choices=[('desc', 'desc'), ('asc', 'asc')], default='desc', max_length=5)),
                ('sort', models.CharField(choices=[('activity', 'activity'), ('creation', 'creation'), ('votes', 'votes'), ('relevance', 'relevance')], default='activity', max_length=10)),
            ],
        ),
    ]
