# Generated by Django 3.1.1 on 2020-09-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_auto_20200911_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShallowUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reputation', models.IntegerField()),
                ('display_name', models.CharField(max_length=200)),
                ('profile_image', models.URLField()),
                ('link', models.URLField()),
                ('user_type', models.CharField(choices=[('unregistered', 'unregistered'), ('registered', 'registered'), ('moderator', 'moderator'), ('team_admin', 'team_admin'), ('does_not_exist', 'does_not_exist')], default='registered', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_answered', models.BooleanField()),
                ('view_count', models.IntegerField()),
                ('answer_count', models.IntegerField()),
                ('score', models.IntegerField()),
                ('last_activity_date', models.IntegerField()),
                ('creation_date', models.IntegerField()),
                ('content_license', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.shallowuser')),
            ],
        ),
    ]
