# Generated by Django 3.1.1 on 2020-09-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_question_shallowuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHash',
            fields=[
                ('query_param_hash', models.IntegerField(primary_key=True, serialize=False)),
                ('question_ids', models.CharField(max_length=500)),
                ('has_more', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='QueryParam',
        ),
    ]
