# Generated by Django 3.1.1 on 2020-09-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_auto_20200917_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhash',
            name='has_more',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='queryhash',
            name='question_ids',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_license',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_activity_date',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='searcher.shallowuser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shallowuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shallowuser',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shallowuser',
            name='profile_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shallowuser',
            name='reputation',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shallowuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('unregistered', 'unregistered'), ('registered', 'registered'), ('moderator', 'moderator'), ('team_admin', 'team_admin'), ('does_not_exist', 'does_not_exist')], default='registered', max_length=20),
        ),
    ]
