# Generated by Django 3.1.1 on 2020-09-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0006_auto_20200917_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_activity_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shallowuser',
            name='reputation',
            field=models.IntegerField(null=True),
        ),
    ]
